version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "layer-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1vg4nk14t0qsp"
s3_prefix = "layer-app"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\""
