version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "app-202100611-001"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1vg4nk14t0qsp"
s3_prefix = "app-202100611-001"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "Environment=\"dev\""
