version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "app-20210530-004"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-k9dwo7tdswva"
s3_prefix = "app-20210530-004"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\""
